### ISSUE TITLE
Exception Value: can't convert complex to float

### ISSUE THREAD

**Issue by martync** [martync/zython#6]
Traceback (most recent call last):
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]

During handling of the above exception ('Recipe' object is not subscriptable), another exception occurred:
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/loader_tags.py", line 76, in super
    return mark_safe(self.render(self.context))
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/defaulttags.py", line 517, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/defaulttags.py", line 517, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/home/martyn/.virtualenvs/zython/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/martyn/zython/django-app/apps/brew/models.py", line 385, in color_image
    srm = int(self.get_srm())
  File "/home/martyn/zython/django-app/apps/brew/models.py", line 405, in get_srm
    return float(recipe_srm)

Exception Type: TypeError at /recipe/guide/style/67/
Exception Value: can't convert complex to float

**Comment by martync** [comment]
Fixed by 4d38c46973545c2179acbf324836cebf67db988a
